name: newsapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  get_storage: ^2.0.3
  get_it:
  flutter_screenutil: ^5.3.1
  dio: ^4.0.6
  url_launcher: ^6.0.18
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Bold.ttf
        - asset: assets/fonts/Sarabun-Medium.ttf
        - asset: assets/fonts/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun-Light.ttf
